### ISSUE TITLE
Add state labels

### ISSUE THREAD

**Issue by st3phhays** [chocolatey/choco-astro#4]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my request.

### Is Your Feature Request Related To A Problem? Please describe.

All Chocolatey repositories have "state" labels, and this repository does not. These would be things like "in progress", "working", "done", and so forth.

### Describe The Solution. Why is it needed?

We need to add state labels, that way we know the state of an issue.

**Comment by st3phhays** [comment]
@gep13 I'm unsure what needs done here to make this happen. Do you have thoughts on this?

**Comment by gep13** [comment]
We would need to setup syncing of labels from the .github repository.  There are a couple of things that need to be done to get this setup, but it doesn't take that long to complete.
